apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-two
  name: app-two
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general-spot
      containers:
      - image: public.ecr.aws/nginx/nginx:{{ .Values.deployment.nginx.image_tag }}
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      tolerations:
      - effect: NoSchedule
        key: general-spot
        operator: Equal
        value: "true"
      volumes:
      - configMap:
          name: app-two-content
        name: content
